cpu-bind=MASK - bp1-gpu035, task  0  0 [88806]: mask 0x80000000000000008000000 set
2023-04-17 16:24:35.042057: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-04-17 16:24:35.445508: I tensorflow/core/common_runtime/gpu/gpu_process_state.cc:214] Using CUDA malloc Async allocator for GPU: 0
2023-04-17 16:24:35.445729: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1525] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 7936 MB memory:  -> device: 0, name: NVIDIA A100-SXM4-80GB MIG 1g.10gb, pci bus id: 0000:41:00.0, compute capability: 8.0
2023-04-17 16:24:58.842028: I tensorflow/stream_executor/cuda/cuda_blas.cc:1774] TensorFloat-32 will be used for the matrix multiplication. This will only be logged once.
2023-04-17 16:24:59.209938: I tensorflow/stream_executor/cuda/cuda_dnn.cc:366] Loaded cuDNN version 8101
WARNING:tensorflow:Skipping full serialization of Keras layer <keras.layers.core.reshape.Reshape object at 0x7fe94c6ebf70>, because it is not built.
2023-04-17 21:25:58.765333: W tensorflow/python/util/util.cc:368] Sets are not currently considered sequences, but this may change in the future, so consider avoiding using them.
WARNING:absl:Found untraced functions such as positional_embedding_layer_call_fn, positional_embedding_layer_call_and_return_conditional_losses, dropout_layer_call_fn, dropout_layer_call_and_return_conditional_losses, positional_embedding_1_layer_call_fn while saving (showing 5 of 790). These functions will not be directly callable after loading.
Traceback (most recent call last):
  File "/user/work/eh19257/ChampSimBPUModelling/models/2_bit_model_tf_transformer.py", line 686, in <module>
    transformer.save(sys.argv[3], save_format='tf')
  File "/sw/lang/anaconda.3.9.7-2021.12-tensorflow.2.7.0/lib/python3.9/site-packages/keras/utils/traceback_utils.py", line 67, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/sw/lang/anaconda.3.9.7-2021.12-tensorflow.2.7.0/lib/python3.9/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/sw/lang/anaconda.3.9.7-2021.12-tensorflow.2.7.0/lib/python3.9/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
TypeError: Unable to serialize [[ 0.          0.          0.         ...  1.          1.
   1.        ]
 [ 0.84147096  0.68156135  0.53316844 ...  1.          1.
   1.        ]
 [ 0.9092974   0.99748     0.9021307  ...  0.9999999   0.99999994
   0.99999994]
 ...
 [ 0.17589758  0.4227187   0.1643498  ...  0.8847002   0.9346019
   0.96304584]
 [-0.7333133   0.9270015   0.6649599  ...  0.8845896   0.9345386
   0.9630099 ]
 [-0.9683193   0.9339683   0.9607745  ...  0.884479    0.9344753
   0.96297395]] to JSON. Unrecognized type <class 'tensorflow.python.framework.ops.EagerTensor'>.
